UniSharp/laravel-filemanager

- src/controllers/Controller.php
- src/controllers/CropController.php
- src/controllers/DeleteController.php
- src/controllers/DownloadController.php
- src/controllers/FolderController.php
- src/controllers/ItemsController.php
- src/controllers/LfmController.php
- src/controllers/RenameController.php
- src/controllers/ResizeController.php
- src/controllers/UploadController.php
All the controllers reference the parent controller with `use App\Http\Controllers\Controller;`. This doesn't work when you have a custom namespace, as the controller file no longer resolves through the `App` namespace.
```
PHP Fatal error:  Class 'App\Http\Controllers\Controller' not found in dir/vendor/Unisharp/laravel-filemanager/src/controllers/LfmController.php on line 15
```
To remedy this, I created a new abstract controller so that all the controllers can extend it instead of extending the one in an unknown namespace.
See https://github.com/tsawler/laravel-filemanager/pull/48
> Fix controllers extending controller in unknown namespace.

- src/Events/ImageWasDeleted.php
- src/Events/ImageWasRenamed.php
- src/controllers/DeleteController.php
- src/controllers/RenameController.php
- Add new event on RenameController
- Add new event on DeleteController
Allow users to manage listeners on rename and delete files (for SQL
manipulation for example : it’s my case).
> Add new events to manage Delete and Rename

- src/controllers/UploadController.php
Use pathinfo to get only the name of file without extension.
> Correction for double extensions (one in the name and the extension)

- src/config/lfm.php
- src/lang/en/lfm.php
- src/views/script.blade.php
When an error occurs after a file is uploaded, nothing happens.
My change adds an error handler with a simple message and a custom message for the "Request entity too large" error.
Also i corrected double file extensions in config.
> Added error handler to file upload and Corrected double file extensions in config

- src/config/lfm.php
- src/lang/ru/lfm.php
- src/routes.php
- src/views/crop.blade.php
- src/views/index.blade.php
- src/views/resize.blade.php
- src/views/script.blade.php
> Add Russian lang

- src/controllers/UploadController.php
CKEditor gets incorrect url to file something like, `/files/1filename.ext` instead of `/files/1/filename.ext` missing slash before filename.
> Fix - CKEditor getting incorrect url to file, after upload

- src/lang/he/lfm.php
Hey.
I've seen that there are several translation but not a Hebrew one.
I thought it would be nice if there was one.
Please do note, Hebrew is an RTL language. I didn't see any way to specify that so I guess the package is LTR only. The hebrew is still fine. 
I suppose Hebrew speakers would prefer the LTR Hebrew version than the English version.
I didn't change the README file, I will let you do that.
> add support for the Hebrew language

- src/controllers/LfmController.php
Hello!
When i try upload image from ckeditor's "image properties" window, in "upload" tab, "/laravel-filemanager/upload" route response JavaScript code has wrong image url.
For example: he returns a '/photos/1577488c96564f.png' string, while real url is '/photos/1/577488c96564f.png'
before:
after:
> Added forgotten last slash in result of getUrl function

- src/config/lfm.php
- src/controllers/LfmController.php
- src/views/index.blade.php
Added config variables so a user can choose to load the image and file manager in a grid or listview. This provides a cleaner solution than to manually fire a click event on the list button when the page is loaded.
I was planning to do this for some time now. The issue below reminded me that having this small feature might be useful: 
https://github.com/UniSharp/laravel-filemanager/issues/147#issuecomment-263456975
Thanks for creating this amazing package, I use it all the time!
Cheers!
> Choose list or gridview for the filemanager using a config variable

- src/LaravelFilemanagerServiceProvider.php
Using singleton method instead share method. Share method is now deprecated.
> Laravel 5.4 fix

- docs/integration.md
This can be useful example especially now when vuejs is more popular within Laravel community. If you are developing component, you don't want to create a button and rely on jQuery. This way you can just open filemanager with javascript and get the results.
> Update example how to use lfm from javascript

- src/config/lfm.php
- src/controllers/LfmController.php
- src/traits/LfmHelpers.php
The added array in the config file applies ini_set() configuration rules in the LfmController constructor.
This helps users who can't  edit php.ini config because of hosting restrictions. Php memory can be temporarily heightened so the problem in [this issue](https://github.com/UniSharp/laravel-filemanager/issues/268) might be prevented.
Any other php.ini configuration can also be edited using this feature, just add the key and value to the php_ini_overrides part of the configuration file.
There are some limitations tough, for example when editing the upload_max_filesize since the request with uploaded files are already received before the setting is edited.
With this implementation the overrides are applied on every class that implements the LfmController. What do you think? Suggestions …
> Added php.ini override feature as configuration option

- src/traits/LfmHelpers.php
fix: when default prefix value changed in file “config/lfm.php”,the generated file url will be inaccessible #288
> fix hard coded prefix

- src/controllers/UploadController.php
Uploading a regular file using laravel-filemanager causes this error:
`Call to undefined method Symfony\Component\HttpFoundation\File\UploadedFile::path()`
According to other places inside the code, the correct method should be `getRealPath()`, after changing both references in the UploadController I was able to upload files without issues. The error only occured when uploading using the "Files" type of the file manager (like a PDF).
> Changed path() method to getRealPath()

- docs/_config.yml
- docs/integration.md
Added Summernote integration documentation
> Added Summernote integration

- composer.json
- docs/installation.md
This PR adds package auto discovery for Laravel 5.5 and up.
Adding service providers and class aliases to config/app.php is no longer necessary if on L5.5
> Auto discovery

- public/js/script.js
When uploading images, as an admin user I would like to know if the upload was successful or not.
> Showing message to user when file successfully uploaded

- public/js/script.js
Fixes #304 
If the file manager is implemented without an editor and does not open a
new popup window (ie. just using as a file browser/upload/download app),
open files using browser's default method instead of trying to access
window.opener (which does not exist).
> Open files without editor

- src/traits/LfmHelpers.php
The problem here is that when its resolving the path for an URL it uses the wrong prefix setting. 
It uses the prefix setting for the laravel-filemanager package. While it should use the urls_prefix setting.
> Fix for #307

- src/traits/LfmHelpers.php
Corrected returned file creation time to 'Y-m-d h:i'. See Issue #417
> Corrected returned file creation time

- src/controllers/UploadController.php
i just added a little fix to return a json response required by ckeditor drag&drop image upload. to dont break anything its necesary add the `responseType=json ` argument to the uploadUrl option.
something like:
```
{
uploadUrl: route_prefix + '/upload?type=Images&responseType=json&_token='
}
```
> json output for ckeditor drag&drop

- src/LfmPath.php
I was having a hell of a time getting `jsonitems` to return any legitimate output. I am using Laravel 5.4.
The issue happens in `LfmPath::pretty()` when it attempts to resolve a new `LfmItem` instance.
```php
return Container::getInstance()->make(LfmItem::class, [$lfm_path, $this->helper]);
```
The problem is that in Laravel 5.4 the `Container::make()` method does not accept the parameters as an argument. You instead have to use `Container::makeWith()`. `Container::make()` was changed in Laravel 5.5 to behave exactly the same as `Container::makeWith()`, so changing the method to `makeWith()` ensures backwards compatibility.
The second problem is that the `Container::makeWith()` method does not accept a non-associate array for the parameters. You instead have to pass an associative array …
> Prevent Container::make() from type-hinting the parameters

- src/LfmPath.php
I encountered an issue within `LfmPath::makeThumbnail()`. 
```php
// generate cropped image content
$image_content = Image::make($original_image->get())
->fit(config('lfm.thumb_img_width', 200), config('lfm.thumb_img_height', 200))
->encode();
$this->setName($file_name)->thumb(true)->storage->save($image_content);
```
`Image::encode()` returns an instance of `Intervention\Image\Image` with attached encoded image data. It then needs to be casted to a string to access the data. For some reason, it is not automatically cast when passed to the `save()` method causing it throw an error.
```
[2018-01-05 10:04:15] dev.ERROR: fstat() expects parameter 1 to be resource, object given {"file":"/home/vagrant/foundation/vendor/league/flysystem/src/Util.php","line":271,"trace":"#0 [internal function]: …
```
> Cast the thumbnail object to a string when saving

- src/views/index.blade.php
I noticed that the download was not working on my project and I've found that the name attribute could not be found on script.js
`
function download(item) {
var data = defaultParameters();
data['file'] = item.name;
location.href = lfm_route + '/download?' + $.param(data);
}
`
It is because the actions has is defined as multiple on index.blade.php
I'm not sure if the expected behavior is to allow multiple downloads (in which case the modificacion should be to iterate though the items on script.js on the download function) or the fix I'm proposing here
> Download action on single element

- src/LfmPath.php
> fix a bug in LfmPath::uploadValidator

- src/views/grid-view.blade.php
- src/views/list-view.blade.php
As mentioned in #520, using apostrophes in file or directory names results in a JavaScript error:
Uncaught SyntaxError: missing ) after argument list
However the proposed fix might not handle double quotes, the most reliable way seems to use `json_encode` (see [this SO question](https://stackoverflow.com/questions/6269188/how-do-i-escape-only-single-quotes)).
> Allow the use of single quotes in names

- src/views/crop.blade.php
- src/views/list-view.blade.php
I need a free crop. Can you put it back
For best practice, I think we should put a small thumbnail to make user still know what is an image
> feat(crop): add free crop and add small thumb on list view

- src/LfmPath.php
The Intervention `Image::save()` method only supports the local filesystem so it fails if like in my case you are using S3.
I've changed it to use the configured disks storage driver to store the output.
> Support thumbnail creation on non-local filesystems

- src/LfmStorageRepository.php
[Laravel recommends](https://laravel.com/docs/5.7/filesystem#driver-prerequisites) using CachedAdapter from `league/flysystem-cached-adapter` to cache driver meta data.
Prior to this commit it wasn't supported by this package and throws the following exception when attempting to upload a file:
```
Call to undefined method League\Flysystem\Cached\CachedAdapter::getPathPrefix() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method League\\Flysystem\\Cached\\CachedAdapter::getPathPrefix() at /SNIP/vendor/unisharp/laravel-filemanager/src/LfmStorageRepository.php:29)
[stacktrace]
#0 /SNIP/vendor/unisharp/laravel-filemanager/src/LfmPath.php(77): UniSharp\\LaravelFilemanager\\LfmStorageRepository->rootPath()
#1 …
```
> Support CacheAdapters

- public/css/dropzone.min.css
- src/LaravelFilemanagerServiceProvider.php
- src/Lfm.php
- src/LfmPath.php
- src/config/lfm.php
- src/views/crop.blade.php
- src/views/resize.blade.php
After second installation of latest commit (I tried just latest commit) I've noticed that the option `use_package_routes` and `url_prefix` is useless and we should register routes manually in `web.php` file (or any other file used to register routes) even when `use_package_routes` is set to `true`.
so I edited `boot` method of `LaravelFilemanagerServiceProvider` to register routes if corresponding option is enabled and  `routes` from `Lfm` to register routes using `url_prefix` option.
> Fix registering package routes

- public/js/script.js
This allows you to integrate this with Fancybox or other lightboxes / iframe embeds.
To integrate with Fancybox 3, modify "stand-along-button.js" and remove the call to `window.open()` and replace it with:
$.fancybox.open({
src: route_prefix + '?type=' + type + '&callback=SetUrl',
type: 'iframe',
opts: {
iframe: {
css: {
width: '900px',
height: '600px'
}
}
}
});
Not even sure if this is the correct way of going about doing this. At best, think of it as an example. I modified the 1.8 version in my current project with similar changes and everything works well, but I don't have the requisite knowledge to know if I'm breaking something.
> Added support for arbitrary callback

- src/Handlers/LfmConfigHandler.php
I got this error when using [**barryvdh/laravel-ide-helper**] to generate phpDoc.
`PHP Fatal error:  Class 'Unisharp\Laravelfilemanager\Handlers\ConfigHandler' not found in C:\....\app\Handlers\LfmConfigHandler.php on line 5`
=> fixed the namespace [ capital S and capital F]
> Fix namespace in LfmConfigHandler

- src/Controllers/DeleteController.php
> escape folder name in delete error handler

- src/LfmItem.php
- tests/LfmItemTest.php
> I really need this so as not to override your classes.
The problem is in **empty directories**. 
When creating **folders**, the system does not check that it is a directory and tries to read it as a file. From there, problems arise when building a **tree**.
Every time the same **Exception** `FileNotFoundException`
In this PR i've added 3 checks with **code**:
```php
if (! $this->isDirectory()) {
//
}
return false;
```
> Fix trouble with empty folders

- src/LfmPath.php
If working dir is "/" normalizeWorkingDir will add double "//" that breaks S3 functionality
> Trim existing slashes before appending new ones

- src/LfmStorageRepository.php
Google Cloud Storage (and S3, but I ran into this with GCS) don't create/store actual directories, so you can't set ACLs on them. Directories are instead inferred from object names with "/" in them.
A $this->disk->makeDirectory() call will fail, but that can be worked around with 'disable_asserts' => true in the filesystem config. A setVisibility call fails hard though, and disable_asserts doesn't help.
This fix works around that by checking to see if the directory that we just created exists. If the filesystem supports directories, the makeDirectory call will either succeed or error if the dir couldn't be created. The dir will either exist by the time we try to setVisibility on it, or we'll have already errored.
If the filesystem doesn't support directories, the makeDirectory call will …
> don't try to set ACL on directory if filesystem doesn't support them

- src/views/index.blade.php
See https://github.com/UniSharp/laravel-filemanager/issues/701
I experienced an issue uploading large files (500MB+) where the user would not see the tick confirmation when the upload was complete. After some investigation (and making sure I have the correct web server and PHP settings to support large file uploads) and making this change it fixed the issue and the user would receive a tick upon upload completion
> Issues with hanging on large file upload

- src/Traits/LfmHelpers.php
This plugin is compatible with Laravel 6 but str_* helpers are not available with
> Fix str_singular

- src/Traits/LfmHelpers.php
- src/views/index.blade.php
- src/views/list-view.blade.php
Laravel 6.x compat.
#903 was not complete. This swaps out all remaining `str_` calls.
> Swap global string helpers for fully-qualified classes.

- src/LfmStorageRepository.php
When using filesystem drives like `S3`, `GCS` or `DO Spaces`, it is recommended that the file is not set to `public` visibility. 
This should be driven by what is setup on laravel's filesystem configuration.
When a S3 bucket doesn't have public visibility, uploading a file with `public` visibility will throw the following error
```
Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on {S3 URL} ; AWS HTTP error: Client error: `PUT {S3 URL}` resulted in a `403 Forbidden`
```
> Don't set public visibility when uploading files.

- src/config/lfm.php
'valid_mime' and 'startup_view' values for 'file' and 'image' categories is vice-versa. I swapped them and it's correct now.
> Fix 'valid_mime' issue in config file

- src/Controllers/LfmController.php
- src/LaravelFilemanagerServiceProvider.php
This PR addresses the following issues:
- no longer requires config to be published, and will load default config automatically.
- if config isn't published, will not fail the route check in the service provider.
- fixes `foreach` loop in LfmController so that it falls back to empty array if config doesn't return a value, thus not breaking the loop.
Fixes #790 
1. `composer require cweagans/composer-patches`
2. Add the following to composer.json:
```json
"extra": {
"patches": {
"unisharp/laravel-filemanager": {
"PR #969: Fix Loading of Config": "https://patch-diff.githubusercontent.com/raw/UniSharp/laravel-filemanager/pull/969.diff"
}
}
}
```
3. Run `composer update`
> Fix Loading of Config

- src/LfmPath.php
- src/config/lfm.php
Instead of overwrite or displaying an error to the user.
After that change if `rename_duplicates` options is enabled:
When user upload a file with a name that exists, lfm try to add suffix with incrementing number like in Windows:
If `rename_duplicates` and `alphanumeric_filename` options are enabled:
When user upload a file with a name that exists, lfm try to add suffix with incrementing number forwarded by underscore:
> Added ability to rename file on duplicate

- public/js/filemanager.js
- public/js/filemanager.min.js
Adds promise based helper function for some neat usage, i.e.
```javascript
filemanager().then(files => {
// do stuff with files
});
```
Handy when one writes custom JS handlers.
Already optimized to cover as much browsers as possible.
Perhaps worth adding somewhere in the docs, too?
> Add helper function with Promise

- public/js/script.js
Fix `getSelectedItems` typo breaking window callbacks for buttons or custom integrations
> Fix getSelectedItems typo breaking callbacks

- .gitignore
- src/LfmItem.php
- src/config/lfm.php
- tests/LfmItemTest.php
- tests/LfmPathTest.php
Added a custom config item_columns for LfmItem columns property. This changes will be very helpful for those people who want to get file path (import excel) selected by UniSharp/laravel-filemanager.
> Added LfmItem property selection via config

- src/Lfm.php
- src/LfmPath.php
- src/LfmStorageRepository.php
Add this 
`setlocale(LC_ALL, 'en_US.UTF-8');` 
before each pathinfo() function to correct the Persian name in upload or list files.
> Fix pathinfo problem with Persian characters

- src/LfmPath.php
The LfmPath storage "url" path would return the "working_dir" path if the folder name was an empty string.
This update will ensure the "url" path will return the "working_dir" with the root slash removed if the folder_name is set to ".".
The reason for this PR is to allow new installations of LFM to work on preexisting folder structures with little configuration.
> Allow config to set the files folder to the root

- src/Lfm.php
Should be pretty self-explanatory.. either of allow_private_folder or allow_shared_folder booleans can be configured (over-ridden) within each 'folder_categories' array within lfm.php config file, and if specified there, these settings replace the 'global' setting.
Enables private/shared folders to be configured in a more fine-grained way for different 'type's.
> enable allow_private_folder & allow_shared_folder to be overridden for each ‘type’

- docs/integration.md
- Replaced  `img` tag with `div`.  The issue causing a missing image preview by addressing the duplication of the 'img' tag in the code. Previously, the use of <img> resulted in the generation of <img><img /> </img>, leading to the absence of a preview.
> Fix duplicate 'img' tag in standalone button image preview

- src/Controllers/ResizeController.php
- src/Lfm.php
- src/lang/en/lfm.php
- src/views/resize.blade.php
Added a 'Copy & Resize' button on the resize window which will keep the original image & create a new image with new size.
> Feat: Add option to store original image before resizing

- src/Lfm.php
> fix: explicitly declare nullable types in constructor for PHP 8.1+

- src/Lfm.php
This pull request updates the module to be fully compatible with PHP 8.4. It resolves deprecation warnings by adjusting the syntax for nullable typed parameters to align with the new PHP 8.4 syntax. This change ensures the module functions correctly without errors in the updated environment.
Reviewers, please pull these changes and test them in a PHP 8.4 environment to confirm the fix. If you have any questions or need more info, let me know.
> patch code for php 8.4

- src/views/tree.blade.php
I believe the section for disk usage in mobile view should be removed. It's been like this for few years.
> Removed unnecessary section in mobile view
