src/views/files.blade.php
src/views/images.blade.php

Click image thumb or file icon to use the file.

click thumb to use file

---

README.md
src/lang/pt-BR/lfm.php
src/views/index.blade.php

This implementation to TinyMCE is ready and tested. But I could not to test with CKEditor.

Implemented TinyMCE support and pt-BR translation

---

doc/integration.md

Needed to update the individual integration example.

resolved #45

---

src/controllers/UploadController.php

keep the Original file name, strip special characters and replace with _

Format filename after uploading

---

src/views/index.blade.php

I've changed the CDN for `jquery` and `jquery-migrate`,  cloudflare supports https.

https support

---

README.md
src/Events/ImageWasUploaded.php
src/controllers/UploadController.php

This PR will add events to upload to the image upload controller. I've added some documentation to get people started
Maybe i add more events. But this is what i currently need.

Event support

---

src/lang/pl/lfm.php

Polish translation for laravel-filemanager

Add polish translation

---

doc/events.md

Added 3 more events to List of events.
Added How to use events using Event Subscribers.

updated events.md

---

src/controllers/UploadController.php

Changed applied exif data orientation with intervention for fix incorrect orientation on upload image from iphone or others devices.

Changed apply exif data orientation

---

src/controllers/DemoController.php
src/routes.php

We can't cache our routes, because closure based routes cannot be cached

fix route caching problem

---

README.md

Added european portughese and romanian languages to readme description

Update readme.md with pt_PT and ro languages

---

src/views/crop.blade.php

crop.blade.php
add function change aspect ratio

crop view - add change aspect ratio

---

src/lang/fr/lfm.php

Added french translation for nav-sort, nav-sort-alphabetic, nav-sort-time

French translation for sort

---

src/controllers/RedirectController.php
src/controllers/UploadController.php

pathinfo doesn't support utf8 format string, need to encode at first

Fix utf8filename

---

src/routes.php

fixed typo / case sensitive the 'files' route

---

src/views/resize.blade.php

When one is resizing the new height and width are not being passed to the controller. This resolves that.

added new height and width for the file being resized

---

src/lang/zh-CN/lfm.php
src/lang/zh-TW/lfm.php

Update Chinese Language Translation(simplified Chinese and traditional Chinese)

Update Chinese Language Translation

---

src/controllers/UploadController.php

CKEditor useFile function was returning different filename.

CKEditor useFile fix

---

docs/config.md
src/config/lfm.php
src/controllers/UploadController.php

With my host I don't have access to change file permissions.   I would like to be able to upload files without getting an error because of chmod permission denied.

Create an option to perform chmod

---

docs/events.md

Please reject if this PR will not be helpful. :)

Updated docs for events

---

composer.json

Add Laravel 5.8 support

---

src/lang/uk/lfm.php

Translations for new strings from _en/lfm.php_

Update uk translations

---

composer.json

Added Laravel 6 support

---

src/views/index.blade.php

Fixes assets loading problem when site url scheme is http://

---

composer.json
src/Lfm.php
src/LfmItem.php
src/Middlewares/MultiUser.php

Fix deprecated helper functions, then add support for laravel 6

---

src/Controllers/FolderController.php

fixed #852

---

src/Controllers/UploadController.php

upload returns array

---

src/lang/ru/lfm.php

just added missing Russian translations

Added missing Russian translations

---

src/lang/pt-BR/lfm.php

I added the translation of some items that were not present in the pt-BR version

translation of some items pt-BR

---

src/Lfm.php

Fix duplicate route name

---

src/LfmPath.php

put cropped images as public so they are visible in file-manager window

make thumbnails public

---

src/lang/hu/lfm.php

Added some missing hungarian translations

Hungarian translation fix

---

src/LfmItem.php

#869 fix time displaying

---

composer.json
src/lang/pl/lfm.php

Laravel 8 support
Missing polish translations

Laravel 8 support && Missing polish translations

---

src/lang/ro/lfm.php

Added missing translations for romanian language

Add romanian translations

---

src/Controllers/UploadController.php

Add response 'uploaded' upload image for CKEDITOR 4.

Add response uploaded data for CKEDITOR 4

---

src/LfmPath.php

ZZZZ.jpg should not come before aaaa.jpg

Fix case sensitive sorting issue

---

src/lang/nl/lfm.php

Added Dutch translations

---

src/Controllers/UploadController.php

Fixed docblock in `UploadController` (method `upload()`)

Fixed docblock in UploadController

---

src/views/index.blade.php

some countries in SEA having issue connecting maxcdn.bootstrapcdn.com for past few months, contacted provider - no luck.

update cdn - all to jsdelivr.net

---

src/Controllers/RenameController.php

Fix where renaming a file fails when alphanumeric directory is true

---

src/lang/tr/lfm.php

New keyword translation complete

Update Turkish language file

---

src/lang/az/lfm.php

Added missing translations

---

src/lang/nl/lfm.php

Added message-drop NL translation to fix undefined

[FIX] Added message-drop NL translation to fix undefined

---

src/routes.php

Colliding route name fix.

---

src/LfmStorageRepository.php

add s3 public visibility when upload file
some of file doesnt set public only thumbnail currently visible to public

set public visibility when uploading file

---

src/Controllers/DownloadController.php

i found this bug when i'm trying to connect with asw s3 storage

available downloading from s3

---

src/Controllers/CropController.php
src/Controllers/ResizeController.php

I just followed your example in https://github.com/UniSharp/laravel-filemanager/commit/539a1904b1b85f50a30810c0cbef28c647ac5e93 and completed 2 TODOs in CropController and ResizeController.

support intervention/image v3
